version: '3.8'
services:
  backend:
    build: .
    container_name: bend-backend
    ports:
      - '8081:8081'
    environment:
      DB_DIALECT: 'postgres'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'example'
      DB_NAME: 'bend-backend-task'
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'example'
      POSTGRES_DB: 'bend-backend-task'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
